title: 学海无涯，回头是岸
author: yanshouwang
email: yanshouwang@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub Pages 从入门到放弃
# social links
twitter_username: yanshouwang
github_username:  yanshouwang

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman